const REPO_OWNER = 'anujyadav70750';
const REPO_NAME = 'skill-foundry';
const DEFAULT_BRANCH = 'main';
const MAX_IMAGE_BYTES = 8 * 1024 * 1024;
const MAX_RESOURCE_BYTES = 200 * 1024;
const MAX_CONTACT_NAME = 100;
const MAX_CONTACT_EMAIL = 254;
const MAX_CONTACT_SUBJECT = 160;
const MAX_CONTACT_MESSAGE = 5000;

const corsHeaders = (request) => { const origin = request.headers.get('Origin'); const allowed = origin && new URL(request.url).origin === origin ? origin : null; return allowed ? { 'Access-Control-Allow-Origin': allowed, 'Vary': 'Origin' } : {}; };
const json = (body, status = 200, request = null) => new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store', ...(request ? corsHeaders(request) : {}) } });
const safeFilename = (name) => String(name || 'image').normalize('NFKD').replace(/[^a-zA-Z0-9._-]+/g, '-').replace(/^-+|-+$/g, '').toLowerCase() || 'image';
const toBase64 = (bytes) => { let binary = ''; const chunk = 0x8000; for (let i = 0; i < bytes.length; i += chunk) binary += String.fromCharCode(...bytes.subarray(i, i + chunk)); return btoa(binary); };
const githubHeaders = (token) => ({ 'Accept': 'application/vnd.github+json', 'Authorization': `Bearer ${token}`, 'X-GitHub-Api-Version': '2022-11-28', 'User-Agent': 'Skill Foundry Resource Builder', 'Content-Type': 'application/json' });

async function readImage(request) { const contentLength = Number(request.headers.get('Content-Length') || 0); if (contentLength > MAX_IMAGE_BYTES) throw Object.assign(new Error('Image is too large. Maximum size is 8 MB.'), { status: 413 }); const type = request.headers.get('Content-Type') || ''; let fileName = decodeURIComponent(request.headers.get('X-File-Name') || 'image'); let mimeType = type.split(';')[0].trim().toLowerCase(); let bytes; if (type.toLowerCase().startsWith('multipart/form-data')) { const form = await request.formData(); const file = form.get('file'); if (!(file instanceof File)) throw Object.assign(new Error('No image file was received.'), { status: 400 }); fileName = file.name || fileName; mimeType = file.type || mimeType; if (file.size > MAX_IMAGE_BYTES) throw Object.assign(new Error('Image is too large. Maximum size is 8 MB.'), { status: 413 }); bytes = new Uint8Array(await file.arrayBuffer()); } else { if (!mimeType.startsWith('image/')) throw Object.assign(new Error('Only image files are allowed.'), { status: 415 }); bytes = new Uint8Array(await request.arrayBuffer()); if (bytes.byteLength > MAX_IMAGE_BYTES) throw Object.assign(new Error('Image is too large. Maximum size is 8 MB.'), { status: 413 }); } if (!mimeType.startsWith('image/')) throw Object.assign(new Error('Only image files are allowed.'), { status: 415 }); return { bytes, fileName, mimeType }; }
async function uploadImage(request, env) { if (!env.GITHUB_TOKEN) return json({ error: 'GitHub upload is not configured. Add the GITHUB_TOKEN secret in Cloudflare.' }, 503, request); const { bytes, fileName, mimeType } = await readImage(request); const rawExt = fileName.includes('.') ? fileName.split('.').pop().toLowerCase() : (mimeType.split('/')[1] || 'jpg'); const ext = /^[a-z0-9]{1,8}$/.test(rawExt) ? rawExt : 'jpg'; const filename = `${safeFilename(fileName.replace(/\.[^.]+$/, ''))}-${Date.now()}.${ext}`; const path = `public/images/${filename}`; const response = await fetch(`https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/contents/${path}`, { method: 'PUT', headers: githubHeaders(env.GITHUB_TOKEN), body: JSON.stringify({ message: `Add resource image ${filename}`, content: toBase64(bytes), branch: DEFAULT_BRANCH, committer: { name: 'Skill Foundry Resource Builder', email: '41898282+github-actions[bot]@users.noreply.github.com' } }) }); const result = await response.json().catch(() => ({})); if (!response.ok) return json({ error: result.message || `GitHub rejected the image upload (${response.status}).` }, response.status, request); return json({ path: `/images/${filename}`, name: filename }, 200, request); }
const isSameOriginAdminRequest = (request) => { const origin = request.headers.get('Origin'); const referer = request.headers.get('Referer'); const requestOrigin = new URL(request.url).origin; if (origin !== requestOrigin || !referer) return false; try { return new URL(referer).origin === requestOrigin && new URL(referer).pathname.startsWith('/admin'); } catch { return false; } };
const isSameOriginRequest = (request) => { const origin = request.headers.get('Origin'); const requestOrigin = new URL(request.url).origin; if (origin) return origin === requestOrigin; const referer = request.headers.get('Referer'); if (!referer) return false; try { return new URL(referer).origin === requestOrigin; } catch { return false; } };
const validEmail = (value) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
async function sendContactMessage(request, env) { if (!isSameOriginRequest(request)) return json({ error: 'Contact requests must come from the Skill Foundry website.' }, 403, request); if (!env.RESEND_API_KEY || !env.CONTACT_EMAIL || !env.CONTACT_FROM_EMAIL) return json({ error: 'Contact email delivery is not configured yet.' }, 503, request); let body; try { body = await request.json(); } catch { return json({ error: 'Invalid contact request.' }, 400, request); } const name = String(body?.name || '').trim(); const email = String(body?.email || '').trim().toLowerCase(); const subject = String(body?.subject || '').trim(); const message = String(body?.message || '').trim(); const honeypot = String(body?.website || '').trim(); if (honeypot) return json({ ok: true }, 200, request); if (!name || name.length > MAX_CONTACT_NAME) return json({ error: 'Please enter a valid name.' }, 400, request); if (!email || email.length > MAX_CONTACT_EMAIL || !validEmail(email)) return json({ error: 'Please enter a valid email address.' }, 400, request); if (!subject || subject.length > MAX_CONTACT_SUBJECT) return json({ error: 'Please enter a subject.' }, 400, request); if (!message || message.length > MAX_CONTACT_MESSAGE) return json({ error: 'Please enter a message of up to 5,000 characters.' }, 400, request); const text = ['New message from the Skill Foundry contact form', '', `Name: ${name}`, `Email: ${email}`, `Subject: ${subject}`, '', message].join('\n'); const response = await fetch('https://api.resend.com/emails', { method: 'POST', headers: { Authorization: `Bearer ${env.RESEND_API_KEY}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ from: env.CONTACT_FROM_EMAIL, to: [env.CONTACT_EMAIL], reply_to: email, subject: `[Skill Foundry Contact] ${subject}`, text }) }); const result = await response.json().catch(() => ({})); if (!response.ok) return json({ error: result?.message || 'We could not send your message right now. Please try again later.' }, 502, request); return json({ ok: true }, 200, request); }
async function publishResource(request, env) { if (!env.GITHUB_TOKEN) return json({ error: 'GitHub publishing is not configured. Add the GITHUB_TOKEN secret in Cloudflare.' }, 503, request); if (!isSameOriginAdminRequest(request)) return json({ error: 'Publishing is available only from the admin builder.' }, 403, request); let body; try { body = await request.json(); } catch { return json({ error: 'Invalid publish request.' }, 400, request); } const slug = String(body?.slug || '').trim(); const content = String(body?.content || ''); if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) return json({ error: 'Invalid resource slug.' }, 400, request); if (!content.startsWith('---')) return json({ error: 'Resource content is missing frontmatter.' }, 400, request); if (new TextEncoder().encode(content).byteLength > MAX_RESOURCE_BYTES) return json({ error: 'Resource content is too large.' }, 413, request); const path = `src/content/resources/${slug}.md`; const endpoint = `https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/contents/${path}`; const existing = await fetch(`${endpoint}?ref=${DEFAULT_BRANCH}`, { headers: githubHeaders(env.GITHUB_TOKEN) }); if (existing.ok) return json({ error: `A resource with the slug \"${slug}\" already exists. Choose a different slug.` }, 409, request); if (existing.status !== 404) { const result = await existing.json().catch(() => ({})); return json({ error: result.message || `Could not check the resource path (${existing.status}).` }, existing.status, request); } const response = await fetch(endpoint, { method: 'PUT', headers: githubHeaders(env.GITHUB_TOKEN), body: JSON.stringify({ message: `Publish resource ${slug}`, content: toBase64(new TextEncoder().encode(content)), branch: DEFAULT_BRANCH, committer: { name: 'Skill Foundry Resource Builder', email: '41898282+github-actions[bot]@users.noreply.github.com' } }) }); const result = await response.json().catch(() => ({})); if (!response.ok) return json({ error: result.message || `GitHub rejected the resource publish (${response.status}).` }, response.status, request); return json({ path, slug, url: `/resources/${slug}/` }, 201, request); }

const getToolIconUrl = async (targetUrl) => {
  let target; try { target = new URL(targetUrl); } catch { return ''; }
  if (!['http:', 'https:'].includes(target.protocol)) return '';
  const fallback = `${target.origin}/favicon.ico`;
  const iconScore = (candidate) => { const href = String(candidate.href || '').toLowerCase(); const rel = String(candidate.rel || '').toLowerCase(); const type = String(candidate.type || '').toLowerCase(); const size = Number(candidate.size || 0); let score = 0; if (rel.includes('manifest-icon')) score += 90000; if (rel.includes('apple-touch-icon')) score += 80000; if (rel.includes('icon') && type.includes('svg')) score += 70000; if (rel.includes('icon')) score += 40000; if (rel.includes('mask-icon')) score += 10000; if (type.includes('svg') || href.endsWith('.svg')) score += 5000; score += Math.min(size * size, 65536); return score; };
  const parseIconLinks = (html, baseUrl) => { const found = []; const tagRe = /<link\b[^>]*>/gi; let match; while ((match = tagRe.exec(html))) { const tag = match[0]; const rel = (tag.match(/\brel\s*=\s*[\"']([^\"']+)[\"']/i)?.[1] || '').toLowerCase(); const href = tag.match(/\bhref\s*=\s*[\"']([^\"']+)[\"']/i)?.[1]; if (!href || !/(^|\s)(icon|shortcut|apple-touch-icon|mask-icon)(\s|$)/i.test(rel)) continue; const type = tag.match(/\btype\s*=\s*[\"']([^\"']+)[\"']/i)?.[1] || ''; const sizes = tag.match(/\bsizes\s*=\s*[\"']([^\"']+)[\"']/i)?.[1] || ''; const size = Math.max(0, ...sizes.split(/\s+/).map((x) => { const m = x.match(/(\d+)x(\d+)/i); return m ? Number(m[1]) : 0; })); try { found.push({ href: new URL(href, baseUrl).href, rel, type, size }); } catch {} } return found; };
  try { const landing = await fetch(target.href, { method: 'GET', headers: { 'User-Agent': 'Mozilla/5.0 Skill Foundry Logo Fetcher' }, redirect: 'follow' }); const landingUrl = landing.url || target.href; const resolvedOrigin = new URL(landingUrl).origin; const htmlType = landing.headers.get('content-type') || ''; if (htmlType.includes('text/html')) { const html = await landing.text(); const links = parseIconLinks(html, landingUrl); const manifestHref = html.match(/<link\b[^>]*\brel\s*=\s*[\"'](?:manifest|web-app-manifest)[\"'][^>]*\bhref\s*=\s*[\"']([^\"']+)[\"']/i)?.[1] || html.match(/<link\b[^>]*\bhref\s*=\s*[\"']([^\"']+)[\"'][^>]*\brel\s*=\s*[\"'](?:manifest|web-app-manifest)[\"']/i)?.[1]; if (manifestHref) { try { const manifestUrl = new URL(manifestHref, landingUrl).href; const manifestResponse = await fetch(manifestUrl, { headers: { 'User-Agent': 'Mozilla/5.0 Skill Foundry Logo Fetcher' }, redirect: 'follow' }); if (manifestResponse.ok) { const manifest = await manifestResponse.json(); for (const icon of Array.isArray(manifest.icons) ? manifest.icons : []) { if (!icon?.src) continue; const size = Math.max(0, ...String(icon.sizes || '').split(/\s+/).map((x) => { const m = x.match(/(\d+)x(\d+)/i); return m ? Number(m[1]) : 0; })); try { links.push({ href: new URL(icon.src, manifestUrl).href, rel: 'manifest-icon', type: icon.type || '', size }); } catch {} } } } catch {} } if (links.length) { links.sort((a,b) => iconScore(b) - iconScore(a)); return links[0].href; } } return `${resolvedOrigin}/favicon.ico`; } catch { return fallback; }
};
async function fetchToolLogo(request) { const url = new URL(request.url).searchParams.get('url'); if (!url) return json({ error: 'Tool website URL is required.' }, 400, request); const logoUrl = await getToolIconUrl(url); return logoUrl ? json({ logoUrl }, 200, request) : json({ error: 'Could not resolve the tool logo.' }, 404, request); }
async function fetchToolLogoImage(request) { const url = new URL(request.url).searchParams.get('url'); if (!url) return new Response('Tool website URL is required.', { status: 400 }); const logoUrl = await getToolIconUrl(url); if (!logoUrl) return new Response('', { status: 404 }); try { const response = await fetch(logoUrl, { headers: { 'User-Agent': 'Mozilla/5.0 Skill Foundry Logo Proxy' }, redirect: 'follow' }); if (!response.ok) return new Response('', { status: 404 }); const headers = new Headers(response.headers); headers.set('Cache-Control', 'public, max-age=3600'); headers.delete('set-cookie'); return new Response(response.body, { status: 200, headers }); } catch { return new Response('', { status: 502 }); } }
const injectHeadCss = (response) => new HTMLRewriter().on('head', { element(element) { element.append('<link rel="stylesheet" href="/image-display-fixes.css?v=20260923-10">', { html: true }); element.append('<link rel="stylesheet" href="/tools-workflow-overrides.css?v=20260916-2">', { html: true }); } }).transform(response);
export default { async fetch(request, env) { const url = new URL(request.url); if (request.method === 'OPTIONS' && url.pathname.startsWith('/api/')) return new Response(null, { status: 204, headers: { ...corsHeaders(request), 'Access-Control-Allow-Methods': 'GET,POST,OPTIONS', 'Access-Control-Allow-Headers': 'Content-Type,X-File-Name' } }); if (request.method === 'POST' && url.pathname === '/api/upload-image') { try { return await uploadImage(request, env); } catch (error) { return json({ error: error?.message || 'Image upload failed.' }, error?.status || 500, request); } } if (request.method === 'POST' && url.pathname === '/api/publish-resource') { try { return await publishResource(request, env); } catch (error) { return json({ error: error?.message || 'Resource publish failed.' }, error?.status || 500, request); } } if (request.method === 'POST' && url.pathname === '/api/contact') { try { return await sendContactMessage(request, env); } catch (error) { return json({ error: error?.message || 'Contact message failed.' }, 500, request); } } if (request.method === 'GET' && url.pathname === '/api/tool-logo') { try { return await fetchToolLogo(request); } catch (error) { return json({ error: error?.message || 'Logo lookup failed.' }, 500, request); } } if (request.method === 'GET' && url.pathname === '/api/tool-logo-image') { try { return await fetchToolLogoImage(request); } catch (error) { return new Response('', { status: 500 }); } } let response = await env.ASSETS.fetch(request); const contentType = response.headers.get('content-type') || ''; if (request.method === 'GET' && contentType.includes('text/html')) response = injectHeadCss(response); const isAdminPage = url.pathname === '/admin' || url.pathname.startsWith('/admin/'); if (request.method === 'GET' && isAdminPage && contentType.includes('text/html')) { response = injectBodyScript(response, '/admin/input-output-ratio-fallback.js?v=20260909-6'); response = injectBodyScript(response, '/admin/image-ratio-ui.js?v=20260909-2'); response = injectBodyScript(response, '/admin/thumbnail-crop-ui.js?v=20260909-5'); response = injectBodyScript(response, '/admin/resource-builder.js?v=20260914-5'); response = injectBodyScript(response, '/admin/resource-publisher.js?v=20260914-8'); response = injectBodyScript(response, '/admin/resource-builder-ratio.js?v=20260909-3'); response = injectBodyScript(response, '/admin/image-ratio-publisher.js?v=20260909-2'); response = injectBodyScript(response, '/admin/admin-shell-fix.js?v=20260913-2'); } return response; } };
function injectBodyScript(response, script) { return new HTMLRewriter().on('body', { element(element) { element.append(`<script src="${script}" defer></script>`, { html: true }); } }).transform(response); }
